### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [ScriptTiger/Streamers#1]
Hello! I want to contribute on your project with making logo design. What do you think about it?

Best Regards,
Arslan Şahin
Graphics Designer

**Comment by ScriptTiger** [comment]
If you're offering this to sharpen your skills, by all means you're welcome to it. It's still a new project though and it may be prone to getting scrapped if there's no interest behind it.

**Comment by Arslanshn** [comment]
hello yes to improve myself. I hope you like it :)
https://drive.google.com/drive/folders/1CxoWAOtlwcw0RP6VoxAfdI9oRLfij7qa?usp=sharing

**Comment by ScriptTiger** [comment]
I don't want to be picky for a free picture, but an image of a checklist doesn't seem relevant. It's a good stock icon and I see where you're going since this project is technically a list, but maybe a central image of a TV to allude to streaming would be better? I do like the border, but maybe it could be embellished a bit more to be lighting/fire, something to allude to speed. Thoughts? I hope customer demands/specs can be part of the practice, too :P

**Comment by Arslanshn** [comment]
I care about your ideas :) 
I uploaded the new logo..

**Comment by ScriptTiger** [comment]
That's pretty on point, thank you! I'll add it to the readme as soon as I get time. Just to double-check, should i credit you as "Arslan Şahin"? And you'll be using the CC BY 4.0 license (https://creativecommons.org/licenses/by/4.0/)?

**Comment by Arslanshn** [comment]
I am happy to like you :) yes Arslan Şahin
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons Lisansı" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Bu eser <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"> Creative Commons Atıf 4.0 Uluslararası Lisansı</a> ile lisanslanmıştır.

**Comment by ScriptTiger** [comment]
Feel free to look through my other repositories if you're interested in more practice :)

**Comment by Arslanshn** [comment]
Hello script. Yes, maybe. I can not see the logo I made on the Readme screen

**Comment by ScriptTiger** [comment]
I saw you are accepting BTC, so I hope it's okay I linked your profile to give you some visibility. Thank you again! I will be using the other square logo for an icon set later if this project gains any traction.
